services:
  postgres:
    image: postgres:13.3-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
    - ./postgres/binary/dbdata:/var/lib/postgresql/data
    - ./postgres/binary/dbroot:/root
    - ./init:/docker-entrypoint-initdb.d:ro
    - ./resources:/resources:ro
  spark-master:
    image: bitnamilegacy/spark:3.5.3-debian-12-r0
    environment:
      JDK_JAVA_OPTIONS: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
      SPARK_MODE: master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - "./spark-logs:/spark/logs"
      - ./target:/opt/spark-apps

  spark-worker:
    image: bitnamilegacy/spark:3.5.3-debian-12-r0
    depends_on:
      - spark-master
    environment:
      JDK_JAVA_OPTIONS: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - "./spark-logs:/spark/logs"

  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/logs:/var/log/clickhouse-server